apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-api
  annotations:
    github.com/project-slug: dev-future-tech/product-api
spec:
  type: other
  lifecycle: unknown
  owner: guests
