apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-api
  annotations:
    github.com/project-slug: dev-future-tech/product-api
    backstage.io/adr-location: ./docs/adrs
    backstage.io/techdocs-ref: dir:.
    jira/project-key: OPC
    jira/component: 'product-api'
    jira/token-type: Bearer
  links:
    - url: http://localhost:8080/product-api/requirements
      title: Business requirements
      icon: idea
    - url: http://localhost:8080/product-api/latest
      title: Latest release notes
      icon: note

spec:
  type: service
  lifecycle: production
  owner: user:anthonyikeda
  system: online-retail
  providesApis:
    - product-api
