insert into products(product_name, sku, description, updated_date) values('Sauce - Ranch Dressing', '49349-114', 'Polygala ambigua Nutt.', ${now});
insert into products(product_name, sku, description, updated_date) values('Soup - Campbells, Beef Barley', '55319-160', 'Cyperus lupulinus (Spreng.) Marcks ssp. macilentus (Fernald) Marcks', ${now});
insert into products(product_name, sku, description, updated_date) values('Chick Peas - Dried', '0135-0196', 'Muhlenbergia uniflora (Muhl.) Fernald', ${now});
insert into products(product_name, sku, description, updated_date) values('Soup - Campbells Asian Noodle', '31722-525', 'Phemeranthus brevicaulis (S. Watson) Kiger', ${now});
insert into products(product_name, sku, description, updated_date) values('Doilies - 5, Paper', '16477-185', 'Polypremum L.', ${now});
insert into products(product_name, sku, description, updated_date) values('Cauliflower', '65342-1007', 'Lonicera albiflora Torr. & A. Gray', ${now});
insert into products(product_name, sku, description, updated_date) values('Milk - Skim', '36987-1448', 'Citharexylum brachyanthum (A. Gray) A. Gray', ${now});
insert into products(product_name, sku, description, updated_date) values('Oranges - Navel, 72', '25021-119', 'Epilobium densiflorum (Lindl.) Hoch & P.H. Raven', ${now});
insert into products(product_name, sku, description, updated_date) values('Muffin Batt - Ban Dream Zero', '42507-179', 'Urospermum Scop.', ${now});
insert into products(product_name, sku, description, updated_date) values('Cabbage - Nappa', '55312-181', 'Ruppia cirrhosa (Petagna) Grande', ${now});
insert into products(product_name, sku, description, updated_date) values('Beans - Turtle, Black, Dry', '43063-502', 'Hesperevax acaulis (Kellogg) Greene var. acaulis', ${now});
insert into products(product_name, sku, description, updated_date) values('Coffee Decaf Colombian', '52125-600', 'Cuscuta compacta Juss. ex Choisy var. efimbriata Yunck.', ${now});
insert into products(product_name, sku, description, updated_date) values('Sugar - Splenda Sweetener', '57337-025', 'Veratrum virginicum (L.) W.T. Aiton', ${now});
insert into products(product_name, sku, description, updated_date) values('Ecolab - Hobart Washarm End Cap', '64720-106', 'Juncus validus Coville', ${now});
insert into products(product_name, sku, description, updated_date) values('Veal - Insides, Grains', '41616-931', 'Astragalus collinus Douglas ex G. Don var. laurentii (Rydb.) Barneby', ${now});
insert into products(product_name, sku, description, updated_date) values('Table Cloth 81x81 Colour', '51346-132', 'Hordeum jubatum L. ssp. intermedium Bowden', ${now});
insert into products(product_name, sku, description, updated_date) values('Extract - Rum', '11419-001', 'Cyanea parvifolia (Forbes) Lammers, Givnish & Systma', ${now});
insert into products(product_name, sku, description, updated_date) values('Turnip - Wax', '0363-0063', 'Physcomitrella patens (Hedw.) Bruch & Schimp.', ${now});
insert into products(product_name, sku, description, updated_date) values('Lighter - Bbq', '66336-047', 'Gouania meyenii Steud.', ${now});
insert into products(product_name, sku, description, updated_date) values('Chocolate - Liqueur Cups With Foil', '36987-1433', 'Viola ×subaffinis House', ${now});
insert into products(product_name, sku, description, updated_date) values('Lid - 3oz Med Rec', '48951-8009', 'Crataegus rigens Beadle', ${now});
insert into products(product_name, sku, description, updated_date) values('Soup - Base Broth Beef', '54868-0057', 'Penstemon euglaucus English', ${now});
insert into products(product_name, sku, description, updated_date) values('Sprouts - Brussel', '58118-1344', 'Stellaria alsine Grimm', ${now});
insert into products(product_name, sku, description, updated_date) values('Flavouring Vanilla Artificial', '0268-6216', 'Psorothamnus polydenius (Torr. ex S. Watson) Rydb. var. polydenius', ${now});
insert into products(product_name, sku, description, updated_date) values('Chips - Doritos', '49944-001', 'Duboisia R. Br.', ${now});
insert into products(product_name, sku, description, updated_date) values('Wine - Red, Gamay Noir', '0268-1193', 'Corchorus hirsutus L.', ${now});
insert into products(product_name, sku, description, updated_date) values('Pepper - Green', '55154-9377', 'Smelowskia calycina (Stephan ex Willd.) C.A. Mey. var. americana (Regel & Herder) Drury & Rollins', ${now});
insert into products(product_name, sku, description, updated_date) values('Glass Clear 8 Oz', '54473-186', 'Astragalus misellus S. Watson', ${now});
insert into products(product_name, sku, description, updated_date) values('Juice - Pineapple, 48 Oz', '68196-930', 'Mimulus tilingii Regel var. caespitosus (Greene) A.L. Grant', ${now});
insert into products(product_name, sku, description, updated_date) values('Wine - Cahors Ac 2000, Clos', '0781-6202', 'Cynanchum angustifolium Pers.', ${now});