apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: product-ns
spec:
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-sidecar
          image: anthonyikeda/product-sidecar:0.0.1
          ports:
            - containerPort: 7080
          imagePullPolicy: Always
        - name: product-api
          image: anthonyikeda/product-api:0.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: database_username
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: database_url
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-api-secrets
                  key: databasePassword
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: rabbitmq_host

