apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: product-ns
spec:
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-sidecar
          image: anthonyikeda/product-sidecar:0.0.2-SNAPSHOT
          ports:
            - containerPort: 7080
            - containerPort: 7081
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              port: 7081
              path: /actuator/health/readiness
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 7081
              path: /actuator/health/liveness
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "150Mi"  # Add the JVM flags to the container envvars
          env:
            - name: JAVA_OPTS
              value: |
                -Xms30m
                -Xmx50m
                -XX:MaxRAM=150M
        - name: product-api
          image: anthonyikeda/product-api:0.0.13-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
            - containerPort: 8091
          readinessProbe:
            httpGet:
              port: 8091
              path: /actuator/health/readiness
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 8091
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 3
          resources:
            requests:
              memory: "215Mi"
            limits:
              memory: "1G"  # Add the JVM flags to the container envvars
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: database_username
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: database_url
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-api-secrets
                  key: databasePassword
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: rabbitmq_host
            - name: PRODUCT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOGGING_LEVEL_ORG_FLOWER_PRODUCTAPI
              value: debug
            - name: JAVA_OPTS
              value: |
                -Xms256m
                -Xmx512m
                -XX:MaxRAM=1G

