name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  image_matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: java-setup
        name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - id: build
        name: Execute build
        run: ./mvnw clean verify
      - id: docker-login
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - id: release
        name: Release to packages
        run: |
          ./mvnw release:prepare release:perform -B -s .maven_settings.xml 
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      - id: artifactId
        name: Get ArtifactId
        run: |
          echo "artifactId=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
      - id: version
        name: Get Version
        run: |
          echo "artifactVersion=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - id: build_image
        name: Build Docker image - no tests
        run: ./mvnw clean verify -DskipTests=true jib:dockerBuild
      - id: docker_push
        name: Push to DockerHub
        run: docker push anthonyikeda/${{env.artifactId}}:${{env.artifactVersion}}
      - id: git_config
        name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
