name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  image_matrix:
    runs-on: ubuntu-latest
    outputs:
      artifactId: ${{ steps.artifactId.outputs.artifactId }}
      version: ${{ steps.version.outputs.version }}
    strategy:
      matrix:
        env: ['clean verify', 'clean verify -DskipTests=true jib:buildTar']
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Execute
        id: build
        run: ./mvnw ${{matrix.env}}
      - name: Get ArtifactId
        id: artifactId
        run: echo "::set-output artifactId=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)"
      - name: Get Version
        id: version
        run: echo "::set-output version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Upload math result for job 2
        id: uploadArtifact
        uses: actions/upload-artifact@v3
        with:
          name: product-tar
          path: target/jib-image.tar


  push:
    needs: image_matrix
    runs-on: ubuntu-latest
    steps:
      - name: download tar
        uses: actions/download-artifact@v3
        with:
          name: product-tar
      - name: load to registry
        run: docker load -i jib-image.tar
      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: anthonyikeda/${{ needs.image_matrix.outputs.artifactId }}:${{ needs.image_matrix.outputs.version }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_HUB_SECRET }}
