name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  image_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['clean verify', 'clean verify -DskipTests=true jib:dockerBuild']
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Execute
        run: ./mvnw ${{matrix.env}}

