name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  image_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['clean verify', 'clean verify -DskipTests=true jib:buildTar']
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Execute
        run: ./mvnw ${{matrix.env}}
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v3
        with:
          name: product-tar
          path: target/jib-image.tar


  push:
    needs: image_matrix
    runs-on: ubuntu-latest
    steps:
      - name: download tar
        uses: actions/download-artifact@v3
        with:
          name: product-tar
      - name: load to registry
        run: docker load -i jib-image.tar
      - name: push to repo
        run: docker images
