name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  image_matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: java-setup
        name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - id: build
        name: Execute build
        run: ./mvnw clean verify jib:dockerBuild
      - id: docker-login
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - id: list_images
        name: list docker images
        run: docker images
      - id: artifactId
        name: Get ArtifactId
        run: |
          "artifactId=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
      - id: version
        name: Get Version
        run: |
          "artifactVersion=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: anthonyikeda/${{env.artifactId}}:${{env.artifactVersion}}
